export {
  OWNER_STAFF_ROLES,
  STAFF_ROLES,
  USER_ROLE_BARBER as STAFF_ROLE_BARBER,
  USER_ROLE_MANAGER as STAFF_ROLE_MANAGER,
  USER_ROLE_RECEPTIONIST as STAFF_ROLE_RECEPTIONIST,
  USER_ROLE_SKINNER as STAFF_ROLE_SKINNER,
} from "./roles";
