export const branchTexts = {
  api: {
    errors: {
      branchInUse: "Chi nhánh đã có dữ liệu liên quan, không thể xoá",
      forbidden: "Bạn không có quyền quản lý chi nhánh",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      missingBranchId: "Thiếu mã chi nhánh",
      missingName: "Vui lòng nhập tên chi nhánh",
      missingAddress: "Vui lòng nhập địa chỉ chi nhánh",
      notFound: "Không tìm thấy chi nhánh",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  ownerBranches: {
    title: "Quản lý chi nhánh",
    description: "Tạo và cập nhật các chi nhánh thuộc tiệm của bạn.",
    createTitle: "Thêm chi nhánh",
    editTitle: "Cập nhật chi nhánh",
    nameLabel: "Tên chi nhánh",
    addressLabel: "Địa chỉ",
    namePlaceholder: "Ví dụ: Chi nhánh Quận 1",
    addressPlaceholder: "Nhập địa chỉ chi nhánh",
    submitCreate: "Tạo chi nhánh",
    submitUpdate: "Lưu thay đổi",
    cancelEdit: "Huỷ chỉnh sửa",
    edit: "Sửa",
    delete: "Xoá",
    deleteConfirm: "Bạn có chắc muốn xoá chi nhánh này?",
    deleting: "Đang xoá...",
    loading: "Đang tải chi nhánh...",
    empty: "Chưa có chi nhánh nào.",
    createdAtLabel: "Ngày tạo",
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      missingName: "Vui lòng nhập tên chi nhánh",
      missingAddress: "Vui lòng nhập địa chỉ chi nhánh",
    },
  },
};
