export const branchTexts = {
  api: {
    errors: {
      branchInUse: "Chi nhánh đã có dữ liệu liên quan, không thể xoá",
      forbidden: "Bạn không có quyền quản lý chi nhánh",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      missingBranchId: "Thiếu mã chi nhánh",
      missingName: "Vui lòng nhập tên chi nhánh",
      missingAddress: "Vui lòng nhập địa chỉ chi nhánh",
      invalidManager: "Manager không hợp lệ hoặc không thuộc tiệm của bạn",
      inactiveBranch: "Chi nhánh đã ngừng hoạt động",
      openVisits: "Cần hoàn thành toàn bộ lượt ghé trước khi ngừng chi nhánh",
      invalidStatus: "Trạng thái chi nhánh không hợp lệ",
      notFound: "Không tìm thấy chi nhánh",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  ownerBranches: {
    title: "Quản lý chi nhánh",
    filterTitle: "Bộ lọc",
    listTitle: "Danh sách chi nhánh",
    searchLabel: "Tìm kiếm",
    searchPlaceholder: "Tìm theo tên hoặc địa chỉ",
    statusLabel: "Trạng thái",
    applyFilters: "Tìm kiếm",
    createAction: "Thêm chi nhánh",
    createTitle: "Thêm chi nhánh",
    detailTitle: "Chi tiết chi nhánh",
    editTitle: "Cập nhật chi nhánh",
    informationTitle: "Thông tin chi nhánh",
    staffTitle: "Danh sách nhân viên",
    editAction: "Chỉnh sửa",
    backToList: "Quay lại danh sách",
    cancel: "Hủy",
    transferStaff: "Điều chuyển nhân viên",
    transferStaffPending: "Tính năng điều chuyển nhân viên sẽ được hoàn thiện sau",
    transferTitle: "Điều chuyển nhân viên",
    transferTargetLabel: "Chi nhánh đích",
    transferTargetPlaceholder: "Chọn chi nhánh",
    transferConfirm: "Điều chuyển",
    transferSuccess: "Đã điều chuyển nhân viên thành công",
    selectStaffToTransfer: "Chọn ít nhất một nhân viên để điều chuyển",
    saveBeforeStaff: "Lưu chi nhánh trước khi thêm nhân viên.",
    staffEmpty: "Chi nhánh chưa có nhân viên.",
    branchNotFound: "Không tìm thấy chi nhánh.",
    readOnlyInactive: "Chi nhánh ngừng hoạt động chỉ có thể xem thông tin.",
    nameLabel: "Tên chi nhánh",
    addressLabel: "Địa chỉ",
    managerLabel: "Manager",
    namePlaceholder: "Ví dụ: Chi nhánh Quận 1",
    addressPlaceholder: "Nhập địa chỉ chi nhánh",
    managerPlaceholder: "Chọn manager",
    managerSearchPlaceholder: "Tìm theo tên đăng nhập",
    managerEmpty: "Không tìm thấy manager",
    noManagerOption: "Chưa phân công",
    submitCreate: "Tạo chi nhánh",
    submitUpdate: "Lưu thay đổi",
    cancelEdit: "Huỷ chỉnh sửa",
    edit: "Sửa",
    delete: "Xoá",
    deactivate: "Ngừng hoạt động",
    activate: "Kích hoạt lại",
    deactivateUnavailable: "Chỉ có thể ngừng khi tất cả lượt ghé đã hoàn thành",
    statusActionUnavailable: "Tính năng sẽ khả dụng sau khi API trạng thái chi nhánh được hoàn thiện",
    loading: "Đang tải chi nhánh...",
    statusUpdating: "Đang cập nhật trạng thái chi nhánh...",
    empty: "Chưa có chi nhánh nào.",
    emptySearch: "Không tìm thấy chi nhánh phù hợp.",
    unassignedManager: "Chưa phân công",
    table: {
      index: "#",
      name: "Tên chi nhánh",
      address: "Địa chỉ",
      manager: "Manager",
      status: "Trạng thái",
      createdAt: "Ngày tạo",
      actions: "Thao tác",
    },
    staffTable: {
      index: "#",
      username: "Tên đăng nhập",
      role: "Vai trò",
      status: "Trạng thái",
      createdAt: "Ngày tạo",
    },
    selectBranch: {
      title: "Chọn chi nhánh",
      empty: "Bạn chưa được phân công chi nhánh đang hoạt động.",
      description: "Chọn chi nhánh để bắt đầu phiên làm việc.",
      action: "Làm việc tại chi nhánh này",
      redirecting: "Đang mở chi nhánh của bạn...",
    },
    unavailable: {
      title: "Chi nhánh đã ngừng hoạt động",
      message: "Tài khoản của bạn đang tạm khóa. Vui lòng liên hệ owner để được chuyển sang chi nhánh khác.",
      logout: "Đăng xuất để dùng tài khoản khác",
    },
    statuses: {
      all: "Tất cả",
      active: "Đang hoạt động",
      inactive: "Ngừng hoạt động",
    },
    toast: {
      created: "Đã tạo chi nhánh thành công",
      updated: "Đã cập nhật chi nhánh thành công",
      activated: "Đã kích hoạt chi nhánh",
      deactivated: "Đã ngừng hoạt động chi nhánh",
    },
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      missingName: "Vui lòng nhập tên chi nhánh",
      missingAddress: "Vui lòng nhập địa chỉ chi nhánh",
    },
  },
};
