export const comboTexts = {
  api: {
    errors: {
      comboInUse: "Combo đã có dữ liệu liên quan, không thể xoá",
      forbidden: "Bạn không có quyền quản lý combo",
      invalidPrice: "Giá combo phải lớn hơn 0",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      invalidServices: "Một hoặc nhiều dịch vụ không thuộc tiệm của bạn",
      missingComboId: "Thiếu mã combo",
      missingDescription: "Vui lòng nhập mô tả combo",
      missingName: "Vui lòng nhập tên combo",
      missingPrice: "Vui lòng nhập giá combo",
      missingServices: "Vui lòng chọn ít nhất một dịch vụ",
      notFound: "Không tìm thấy combo",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  ownerCombos: {
    title: "Quản lý combo",
    description: "Tạo combo từ nhiều dịch vụ lẻ thuộc tiệm của bạn.",
    createTitle: "Thêm combo",
    editTitle: "Cập nhật combo",
    nameLabel: "Tên combo",
    descriptionLabel: "Mô tả combo",
    priceLabel: "Giá combo",
    servicesLabel: "Dịch vụ trong combo",
    copyFromComboLabel: "Copy dịch vụ từ combo có sẵn",
    namePlaceholder: "Ví dụ: Combo cắt gội",
    descriptionPlaceholder: "Nhập mô tả combo",
    pricePlaceholder: "Nhập giá combo",
    copyPlaceholder: "Chọn combo để copy dịch vụ",
    submitCreate: "Tạo combo",
    submitUpdate: "Lưu thay đổi",
    cancelEdit: "Huỷ chỉnh sửa",
    edit: "Sửa",
    delete: "Xoá",
    deleteConfirm: "Bạn có chắc muốn xoá combo này?",
    deleting: "Đang xoá...",
    loading: "Đang tải combo...",
    empty: "Chưa có combo nào.",
    emptyServices: "Chưa có dịch vụ nào để tạo combo.",
    createdAtLabel: "Ngày tạo",
    servicesCountLabel: "Số dịch vụ",
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      invalidPrice: "Giá combo phải lớn hơn 0",
      missingDescription: "Vui lòng nhập mô tả combo",
      missingName: "Vui lòng nhập tên combo",
      missingPrice: "Vui lòng nhập giá combo",
      missingServices: "Vui lòng chọn ít nhất một dịch vụ",
    },
  },
};
