export const comboTexts = {
  api: {
    errors: {
      comboInUse: "Combo đã có dữ liệu liên quan, không thể xoá",
      forbidden: "Bạn không có quyền quản lý combo",
      comboInUseEditBlocked:
        "Combo đã có visit sử dụng, vui lòng nhân bản combo để chỉnh sửa",
      invalidPrice: "Giá combo phải lớn hơn 0",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      invalidServices: "Một hoặc nhiều dịch vụ không thuộc tiệm của bạn",
      missingComboId: "Thiếu mã combo",
      missingDescription: "Vui lòng nhập mô tả combo",
      missingName: "Vui lòng nhập tên combo",
      missingPrice: "Vui lòng nhập giá combo",
      missingServices: "Vui lòng chọn ít nhất một dịch vụ",
      notFound: "Không tìm thấy combo",
      protectedCombo: "Bạn không có quyền thao tác combo này",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  ownerCombos: {
    title: "Quản lý combo",
    listTitle: "Danh sách combo",
    createAction: "Thêm combo",
    createTitle: "Thêm combo",
    editTitle: "Cập nhật combo",
    nameLabel: "Tên combo",
    descriptionLabel: "Mô tả combo",
    priceLabel: "Giá combo",
    servicesLabel: "Dịch vụ trong combo",
    copyFromComboLabel: "Copy dịch vụ từ combo có sẵn",
    namePlaceholder: "Ví dụ: Combo cắt gội",
    descriptionPlaceholder: "Nhập mô tả combo",
    pricePlaceholder: "Nhập giá combo",
    copyPlaceholder: "Chọn combo để copy dịch vụ",
    submitCreate: "Tạo combo",
    submitUpdate: "Lưu thay đổi",
    cancelEdit: "Huỷ chỉnh sửa",
    edit: "Sửa",
    duplicate: "Nhân bản combo",
    delete: "Xoá",
    deleteCancel: "Huỷ",
    deleteConfirmTitle: "Xoá combo",
    deleteConfirmDescription: "Combo bị xoá sẽ không còn xuất hiện khi tạo visit mới.",
    deleting: "Đang xoá...",
    loading: "Đang tải combo...",
    empty: "Chưa có combo nào.",
    emptyDeleted: "Chưa có combo đã xoá.",
    emptyServices: "Chưa có dịch vụ nào để tạo combo.",
    applyFilters: "Áp dụng",
    filterSearchLabel: "Tìm kiếm",
    filterScopeAll: "Tất cả",
    createdAtLabel: "Ngày tạo",
    creatorLabel: "Người tạo",
    deletedAtLabel: "Ngày xoá",
    selectedServicesTotalLabel: "Tổng tiền dịch vụ lẻ",
    servicesCountLabel: "Số dịch vụ",
    priceAboveServicesWarning:
      "Giá combo đang cao hơn tổng giá dịch vụ lẻ. Vẫn có thể lưu nếu đây là giá bạn muốn áp dụng.",
    comboInUseEditBlocked:
      "Combo đã có visit sử dụng. Vui lòng nhân bản combo để chỉnh sửa thông tin mới.",
    copySuffix: " copy",
    table: {
      actions: "Thao tác",
      createdAt: "Ngày tạo",
      creator: "Người tạo",
      index: "#",
      name: "Combo",
      price: "Giá",
      scope: "Phạm vi",
      services: "Dịch vụ bao gồm",
    },
    scopes: {
      branch: "Chi nhánh",
      shop: "Hệ thống",
      unknown: "Chưa xác định",
    },
    statusTabs: {
      active: "Đang hoạt động",
      deleted: "Đã xoá",
    },
    toast: {
      created: "Đã tạo combo",
      deleted: "Đã xoá combo",
      updated: "Đã cập nhật combo",
    },
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      invalidPrice: "Giá combo phải lớn hơn 0",
      missingDescription: "Vui lòng nhập mô tả combo",
      missingName: "Vui lòng nhập tên combo",
      missingPrice: "Vui lòng nhập giá combo",
      missingServices: "Vui lòng chọn ít nhất một dịch vụ",
    },
  },
};
