export const customerTexts = {
  api: {
    errors: {
      duplicatePhone: "Số điện thoại đã tồn tại trong tiệm",
      forbidden: "Bạn không có quyền tra cứu khách hàng",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      missingName: "Vui lòng nhập tên khách hàng",
      missingPhone: "Vui lòng nhập số điện thoại",
      notFound: "Không tìm thấy khách hàng",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  detail: {
    title: "Chi tiết khách hàng",
    description: "Thông tin chi tiết của khách hàng trong tiệm.",
    idLabel: "Mã khách hàng",
    backToLookup: "Quay lại tra cứu",
    barberLabel: "Thợ cắt",
    customerInfoTitle: "Thông tin khách",
    emptySuggestions: "Chưa có dữ liệu để gợi ý.",
    emptyVisits: "Khách hàng chưa có lịch sử ghé tiệm.",
    historyTitle: "Lịch sử ghé tiệm",
    loading: "Đang tải lịch sử khách hàng...",
    noPhotos: "Không có ảnh",
    noServices: "Chưa có dịch vụ",
    noStaff: "Chưa chọn",
    phoneLabel: "Số điện thoại",
    photosLabel: "Ảnh kiểu tóc",
    servicesLabel: "Dịch vụ và combo",
    skinnerLabel: "Skinner",
    suggestionDescription: "Dùng thông tin lần ghé gần nhất để tạo visit mới nhanh hơn.",
    suggestionTitle: "Gợi ý cho visit mới",
    totalPriceLabel: "Tổng tiền",
    visitDateLabel: "Ngày ghé",
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
    },
  },
  lookup: {
    title: "Tra cứu khách hàng",
    description: "Tìm khách theo tên hoặc số điện thoại trong tiệm của bạn.",
    searchLabel: "Tên hoặc số điện thoại",
    searchPlaceholder: "Nhập tên hoặc SĐT khách",
    searchButton: "Tìm khách",
    loading: "Đang tìm khách hàng...",
    emptyBeforeSearch: "Nhập tên hoặc số điện thoại để bắt đầu tra cứu.",
    emptyAfterSearch: "Không tìm thấy khách hàng phù hợp.",
    createOption: "Tạo khách hàng mới",
    createTitle: "Thêm khách hàng",
    nameLabel: "Tên khách hàng",
    phoneLabel: "Số điện thoại",
    namePlaceholder: "Ví dụ: Nguyễn Văn Nam",
    phonePlaceholder: "Ví dụ: 0901234567",
    submitCreate: "Lưu khách hàng",
    cancelCreate: "Huỷ",
    customerInfoTitle: "Thông tin khách",
    phonePrefix: "SĐT",
    lastVisitTitle: "Lần ghé gần nhất",
    noLastVisit: "Chưa có lần ghé nào.",
    servicesLabel: "Dịch vụ đã dùng",
    barberLabel: "Thợ cắt",
    skinnerLabel: "Skinner",
    photosLabel: "Ảnh lần trước",
    noServices: "Chưa có dịch vụ",
    noStaff: "Chưa chọn",
    noPhotos: "Không có ảnh",
    createdAtLabel: "Ngày tạo",
    visitedAtLabel: "Ngày ghé",
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      duplicatePhone: "Số điện thoại đã tồn tại trong tiệm",
      missingName: "Vui lòng nhập tên khách hàng",
      missingPhone: "Vui lòng nhập số điện thoại",
      missingSearch: "Vui lòng nhập tên hoặc số điện thoại",
    },
  },
};
