export const customerTexts = {
  api: {
    errors: {
      forbidden: "Bạn không có quyền tra cứu khách hàng",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      missingName: "Vui lòng nhập tên khách hàng",
      missingPhone: "Vui lòng nhập số điện thoại",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  lookup: {
    title: "Tra cứu khách hàng",
    description: "Tìm khách theo tên hoặc số điện thoại trong tiệm của bạn.",
    searchLabel: "Tên hoặc số điện thoại",
    searchPlaceholder: "Nhập tên hoặc SĐT khách",
    searchButton: "Tìm khách",
    loading: "Đang tìm khách hàng...",
    emptyBeforeSearch: "Nhập tên hoặc số điện thoại để bắt đầu tra cứu.",
    emptyAfterSearch: "Không tìm thấy khách hàng phù hợp.",
    createOption: "Tạo khách hàng mới",
    createTitle: "Thêm khách hàng",
    nameLabel: "Tên khách hàng",
    phoneLabel: "Số điện thoại",
    namePlaceholder: "Ví dụ: Nguyễn Văn Nam",
    phonePlaceholder: "Ví dụ: 0901234567",
    submitCreate: "Lưu khách hàng",
    cancelCreate: "Huỷ",
    customerInfoTitle: "Thông tin khách",
    phonePrefix: "SĐT",
    lastVisitTitle: "Lần ghé gần nhất",
    noLastVisit: "Chưa có lần ghé nào.",
    servicesLabel: "Dịch vụ đã dùng",
    barberLabel: "Thợ cắt",
    skinnerLabel: "Skinner",
    photosLabel: "Ảnh lần trước",
    noServices: "Chưa có dịch vụ",
    noStaff: "Chưa chọn",
    noPhotos: "Không có ảnh",
    createdAtLabel: "Ngày tạo",
    visitedAtLabel: "Ngày ghé",
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      missingName: "Vui lòng nhập tên khách hàng",
      missingPhone: "Vui lòng nhập số điện thoại",
      missingSearch: "Vui lòng nhập tên hoặc số điện thoại",
    },
  },
};
