export const designSystemTexts = {
  actions: {
    cancel: "Hủy",
    copied: "Đã sao chép",
    copy: "Sao chép",
    next: "Tiếp",
    previous: "Trước",
  },
  calendar: {
    days: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
  },
  form: {
    selectItems: "Chọn mục...",
  },
  commandMenu: {
    placeholder: "Tìm lệnh...",
  },
  reference: {
    title: "Design System",
    description: "Trang tham khảo các component global và toàn bộ variant đang có.",
    sections: {
      advanced: "Advanced",
      badges: "Badge và typography",
      buttons: "Buttons",
      display: "Display",
      feedback: "Feedback",
      inputs: "Inputs",
      layout: "Layout",
      legacy: "App primitives",
      shadcn: "shadcn primitives",
      specialized: "Specialized",
    },
    groups: {
      actions: "Actions",
      cards: "Cards",
      controls: "Controls",
      forms: "Forms",
      loading: "Loading",
      navigation: "Navigation",
      overlays: "Overlays",
      status: "Status",
      text: "Text",
    },
    labels: {
      action: "Thao tác",
      active: "Đang hoạt động",
      barber: "Barber",
      branch: "Chi nhánh",
      calendar: "Lịch",
      checkbox: "Checkbox",
      code: "Code",
      commandMenu: "Command menu",
      contextMenu: "Context menu",
      customerName: "Khách hàng",
      danger: "Danger",
      default: "Default",
      description: "Mô tả ngắn cho component.",
      drawerLeft: "Drawer trái",
      drawerRight: "Drawer phải",
      email: "Tên đăng nhập",
      error: "Lỗi",
      ghost: "Ghost",
      info: "Info",
      input: "Input",
      keyboard: "Keyboard",
      modal: "Modal",
      next: "Tiếp tục",
      note: "Ghi chú",
      outline: "Outline",
      password: "Mật khẩu",
      phone: "Số điện thoại",
      popover: "Popover",
      primary: "Primary",
      radio: "Radio",
      search: "Tìm kiếm",
      secondary: "Secondary",
      sheet: "Sheet",
      status: "Trạng thái",
      success: "Success",
      switch: "Switch",
      textarea: "Textarea",
      tooltip: "Tooltip",
      warning: "Warning",
      window: "Window",
    },
    samples: {
      customerName: "Nguyễn Văn Nam",
      description:
        "Nội dung mẫu dùng để kiểm tra spacing, màu sắc và trạng thái responsive.",
      error: "Vui lòng kiểm tra lại dữ liệu.",
      hidePassword: "Ẩn mật khẩu",
      image:
        "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='900' height='600' viewBox='0 0 900 600'%3E%3Crect width='900' height='600' fill='%23171717'/%3E%3Crect x='80' y='80' width='740' height='440' rx='32' fill='%23262626' stroke='%23666666'/%3E%3Ccircle cx='450' cy='270' r='96' fill='%23333333' stroke='%23888888'/%3E%3Cpath d='M310 420h280' stroke='%23eaeaea' stroke-width='18' stroke-linecap='round'/%3E%3Ctext x='450' y='500' text-anchor='middle' fill='%23eaeaea' font-family='Arial' font-size='34'%3EDesign Preview%3C/text%3E%3C/svg%3E",
      longPath: "barbershop-management-system/src/components/global/Specialized.tsx",
      password: "mat-khau-mau",
      phone: "0901234567",
      showPassword: "Hiện mật khẩu",
      snippet: "npm run dev",
      toastDescription: "Dữ liệu mẫu đã được cập nhật.",
      toastTitle: "Thao tác thành công",
    },
    navigation: {
      home: "Home",
      overview: "Overview",
      settings: "Settings",
      visits: "Visits",
    },
    options: {
      haircut: "Cắt tóc",
      massage: "Massage",
      wash: "Gội đầu",
    },
    code: {
      variant: "const variant = 'primary';",
    },
    keys: {
      command: "⌘",
      commandMenu: "K",
    },
    actions: {
      clear: "Xóa",
      close: "Đóng",
      copy: "Sao chép",
      delete: "Xóa dữ liệu",
      dismiss: "Bỏ qua",
      openCommandMenu: "Mở command menu",
      openDrawerLeft: "Mở drawer trái",
      openDrawerRight: "Mở drawer phải",
      openLightbox: "Mở lightbox",
      openModal: "Mở modal",
      openSheet: "Mở sheet",
      retry: "Thử lại",
      save: "Lưu",
      select: "Chọn",
      submit: "Gửi",
      update: "Cập nhật",
    },
  },
};
