import {
  StaffReportStatus,
  USER_ROLE_BARBER,
  USER_ROLE_MANAGER,
  USER_ROLE_OWNER,
  USER_ROLE_RECEPTIONIST,
  USER_ROLE_SKINNER,
} from "@/constants/common";
import type { ReportPageRole } from "@/types";

export const reportTexts = {
  api: {
    errors: {
      forbidden: "Forbidden",
      invalidDateRange: "Khoảng ngày báo cáo không hợp lệ.",
      serverError: "Server error",
      unauthorized: "Unauthorized",
    },
  },
  dateRange: {
    fromDateLabel: "Từ ngày",
    label: "Chọn thời gian",
    toDateLabel: "Đến ngày",
  },
  manager: {
    description:
      "Report API chưa implement, màn hình này đang giữ placeholder theo spec.",
    empty: "Chưa có dữ liệu báo cáo quản lý.",
    filtersTitle: "Bộ lọc",
    mockNotice:
      "Dữ liệu báo cáo quản lý đang là placeholder cho tới khi Report API hoàn tất.",
    tableTitle: "Bảng dữ liệu",
    title: "Báo cáo",
  },
  management: {
    branches: {
      title: "Báo cáo chi nhánh",
    },
    combos: {
      title: "Báo cáo combo",
    },
    revenue: {
      title: "Báo cáo doanh thu",
    },
    services: {
      title: "Báo cáo dịch vụ",
    },
    staff: {
      title: "Báo cáo nhân viên",
    },
  },
  personal: {
    comboCountLabel: "Combo đã làm",
    description: "Theo dõi số lượng dịch vụ, combo và dịch vụ nổi bật của bạn.",
    empty: "Chưa có dữ liệu báo cáo cá nhân.",
    fullNameLabel: "Họ và tên",
    generalInfoTitle: "Thông tin chung",
    chooseSpecificMonth: "Chọn tháng",
    loading: "Đang tải báo cáo cá nhân",
    metricCustomersServed: "Khách đã phục vụ",
    metricCompletedVisits: "Visit hoàn thành",
    monthPickerLabel: "Chọn tháng báo cáo",
    periodOptions: {
      all: "Tất cả thời gian",
      currentMonth: "Tháng hiện tại",
      month: "Tháng",
      year: "Năm hiện tại",
    },
    periodTitle: "Kỳ báo cáo",
    roleLabel: "Role",
    serviceCountLabel: "Dịch vụ đã làm",
    title: "Báo cáo cá nhân",
    topCustomerTitle: "Khách phục vụ nhiều nhất",
    topItemCount: (count: number) => `${count} lượt`,
    topItemTitle: "Dịch vụ thực hiện nhiều nhất",
  },
  roles: {
    [USER_ROLE_BARBER]: "Barber",
    [USER_ROLE_MANAGER]: "Quản lý",
    [USER_ROLE_OWNER]: "Chủ tiệm",
    [USER_ROLE_RECEPTIONIST]: "Reception",
    [USER_ROLE_SKINNER]: "Skinner",
  } satisfies Record<ReportPageRole, string>,
  branchReport: {
    allStatuses: "Tất cả",
    applyFilters: "Áp dụng",
    columns: {
      action: "Chi tiết",
      branch: "Chi nhánh",
      customers: "Khách",
      revenue: "Doanh thu",
      services: "Số dịch vụ/combo",
      status: "Trạng thái",
      visits: "Lượt ghé",
    },
    detailColumns: {
      barber: "Barber",
      completedAt: "Hoàn thành",
      customer: "Khách",
      receptionist: "Reception",
      revenue: "Doanh thu",
      services: "Số dịch vụ/combo",
      skinner: "Skinner",
      visit: "Visit",
    },
    detailPageSummary: "Trang {page}/{totalPages} · {total} visit",
    empty: "Chưa có dữ liệu báo cáo chi nhánh.",
    filtersTitle: "Bộ lọc",
    loading: "Đang tải báo cáo chi nhánh",
    loadingDetails: "Đang tải chi tiết báo cáo chi nhánh",
    periodLabel: "Kỳ báo cáo",
    retryDetails: "Thử lại",
    statusLabel: "Trạng thái",
    statusLabels: {
      active: "Đang hoạt động",
      inactive: "Ngừng hoạt động",
    },
    tableTitle: "Bảng chi nhánh",
    viewDetails: "Xem",
  },
  staffReport: {
    allBranches: "Tất cả chi nhánh",
    allRoles: "Tất cả vai trò",
    branchLabel: "Chi nhánh",
    columns: {
      action: "Chi tiết",
      branch: "Chi nhánh",
      customers: "Khách",
      role: "Vai trò",
      services: "Số dịch vụ/combo",
      staff: "Nhân viên",
      status: "Trạng thái",
      visits: "Visit",
    },
    detailColumns: {
      branch: "Chi nhánh",
      completedAt: "Hoàn thành",
      customer: "Khách",
      item: "Dịch vụ/combo",
      role: "Phụ trách",
      visit: "Visit",
    },
    empty: "Chưa có dữ liệu báo cáo nhân viên.",
    filtersTitle: "Bộ lọc",
    currentBranchLabel: "Thông tin chi nhánh",
    detailPageSummary: "Trang {page}/{totalPages} · {total} dòng",
    applyFilters: "Áp dụng",
    loading: "Đang tải báo cáo nhân viên",
    loadingDetails: "Đang tải chi tiết báo cáo nhân viên",
    retryDetails: "Thử lại",
    managerScopeNotice: "Dữ liệu đang được giới hạn theo chi nhánh đang làm việc.",
    periodLabel: "Kỳ báo cáo",
    receptionistVisitItem: "Visit tiếp nhận",
    roleLabel: "Vai trò",
    statusLabels: {
      [StaffReportStatus.Active]: "Đang làm việc",
      [StaffReportStatus.BranchSuspended]: "Chi nhánh đóng cửa",
      [StaffReportStatus.Inactive]: "Đã nghỉ việc",
      [StaffReportStatus.Unknown]: "Thiếu phân công",
    },
    tableTitle: "Bảng nhân viên",
    unknownItem: "Dịch vụ chưa xác định",
    unknownRole: "Chưa xác định",
    unknownStaff: "Chưa xác định",
    viewDetails: "Xem",
  },
};
