export const serviceTexts = {
  api: {
    errors: {
      forbidden: "Bạn không có quyền quản lý dịch vụ",
      invalidPrice: "Giá dịch vụ phải lớn hơn 0",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      invalidResponsibleRole: "Người phụ trách dịch vụ không hợp lệ",
      missingName: "Vui lòng nhập tên dịch vụ",
      missingPrice: "Vui lòng nhập giá dịch vụ",
      missingResponsibleRole: "Vui lòng chọn người phụ trách dịch vụ",
      missingServiceId: "Thiếu mã dịch vụ",
      notFound: "Không tìm thấy dịch vụ",
      protectedService: "Bạn không có quyền thao tác dịch vụ này",
      serviceInUse: "Dịch vụ đã có dữ liệu liên quan, không thể xoá",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  ownerServices: {
    title: "Quản lý dịch vụ",
    listTitle: "Danh sách dịch vụ",
    createAction: "Thêm dịch vụ",
    createTitle: "Thêm dịch vụ",
    editTitle: "Cập nhật dịch vụ",
    nameLabel: "Tên dịch vụ",
    priceLabel: "Giá dịch vụ",
    responsibleRoleLabel: "Người phụ trách",
    responsibleRolePlaceholder: "Chọn người phụ trách",
    isHaircutLabel: "Dịch vụ cắt tóc",
    namePlaceholder: "Ví dụ: Cắt tóc nam",
    pricePlaceholder: "Nhập giá dịch vụ",
    submitCreate: "Tạo dịch vụ",
    submitUpdate: "Lưu thay đổi",
    cancelEdit: "Huỷ chỉnh sửa",
    edit: "Sửa",
    delete: "Xoá",
    deleteCancel: "Huỷ",
    deleteConfirmTitle: "Xoá dịch vụ",
    deleteConfirmDescription: "Dịch vụ bị xoá sẽ không còn xuất hiện khi tạo visit mới.",
    deleting: "Đang xoá...",
    loading: "Đang tải dịch vụ...",
    empty: "Chưa có dịch vụ nào.",
    createdAtLabel: "Ngày tạo",
    creatorLabel: "Người tạo",
    branchEmpty: "Toàn shop",
    applyFilters: "Áp dụng",
    filterResponsibleRoleAll: "Tất cả",
    filterSearchLabel: "Tìm kiếm",
    filterScopeAll: "Tất cả",
    haircutBadge: "Cắt tóc",
    table: {
      actions: "Thao tác",
      createdAt: "Ngày tạo",
      creator: "Người tạo",
      index: "#",
      name: "Dịch vụ",
      price: "Giá",
      responsibleRole: "Phụ trách",
      scope: "Phạm vi",
    },
    scopes: {
      branch: "Chi nhánh",
      shop: "Hệ thống",
    },
    toast: {
      created: "Đã tạo dịch vụ",
      deleted: "Đã xoá dịch vụ",
      updated: "Đã cập nhật dịch vụ",
    },
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      invalidPrice: "Giá dịch vụ phải lớn hơn 0",
      invalidResponsibleRole: "Người phụ trách dịch vụ không hợp lệ",
      missingName: "Vui lòng nhập tên dịch vụ",
      missingPrice: "Vui lòng nhập giá dịch vụ",
      missingResponsibleRole: "Vui lòng chọn người phụ trách dịch vụ",
    },
    responsibleRoles: {
      barber: "Barber",
      skinner: "Skinner",
    },
  },
};
