export const serviceTexts = {
  api: {
    errors: {
      forbidden: "Bạn không có quyền quản lý dịch vụ",
      invalidPrice: "Giá dịch vụ phải lớn hơn 0",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      invalidResponsibleRole: "Người phụ trách dịch vụ không hợp lệ",
      missingName: "Vui lòng nhập tên dịch vụ",
      missingPrice: "Vui lòng nhập giá dịch vụ",
      missingResponsibleRole: "Vui lòng chọn người phụ trách dịch vụ",
      missingServiceId: "Thiếu mã dịch vụ",
      notFound: "Không tìm thấy dịch vụ",
      serviceInUse: "Dịch vụ đã có dữ liệu liên quan, không thể xoá",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  ownerServices: {
    title: "Quản lý dịch vụ",
    description: "Tạo và cập nhật dịch vụ lẻ thuộc tiệm của bạn.",
    createTitle: "Thêm dịch vụ",
    editTitle: "Cập nhật dịch vụ",
    nameLabel: "Tên dịch vụ",
    priceLabel: "Giá dịch vụ",
    responsibleRoleLabel: "Người phụ trách",
    isHaircutLabel: "Dịch vụ cắt tóc",
    namePlaceholder: "Ví dụ: Cắt tóc nam",
    pricePlaceholder: "Nhập giá dịch vụ",
    submitCreate: "Tạo dịch vụ",
    submitUpdate: "Lưu thay đổi",
    cancelEdit: "Huỷ chỉnh sửa",
    edit: "Sửa",
    delete: "Xoá",
    deleteConfirm: "Bạn có chắc muốn xoá dịch vụ này?",
    deleting: "Đang xoá...",
    loading: "Đang tải dịch vụ...",
    empty: "Chưa có dịch vụ nào.",
    createdAtLabel: "Ngày tạo",
    haircutBadge: "Cắt tóc",
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      invalidPrice: "Giá dịch vụ phải lớn hơn 0",
      invalidResponsibleRole: "Người phụ trách dịch vụ không hợp lệ",
      missingName: "Vui lòng nhập tên dịch vụ",
      missingPrice: "Vui lòng nhập giá dịch vụ",
      missingResponsibleRole: "Vui lòng chọn người phụ trách dịch vụ",
    },
    responsibleRoles: {
      barber: "Barber",
      skinner: "Skinner",
    },
  },
};
