export const staffTexts = {
  api: {
    errors: {
      duplicateUsername: "Tên đăng nhập đã tồn tại trong tiệm",
      forbidden: "Bạn không có quyền quản lý nhân viên",
      invalidBranch: "Chi nhánh không thuộc tiệm của bạn",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      invalidRole: "Vai trò nhân viên không hợp lệ",
      missingPassword: "Vui lòng nhập mật khẩu",
      missingStaffId: "Thiếu mã nhân viên",
      missingUsername: "Vui lòng nhập tên đăng nhập",
      notFound: "Không tìm thấy nhân viên",
      passwordTooShort: "Mật khẩu phải có ít nhất 8 ký tự",
      staffInUse: "Nhân viên đã có dữ liệu liên quan, không thể xoá",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  ownerStaff: {
    title: "Quản lý nhân viên",
    description: "Tạo tài khoản và phân công chi nhánh cho nhân viên.",
    createTitle: "Thêm nhân viên",
    editTitle: "Cập nhật nhân viên",
    usernameLabel: "Tên đăng nhập",
    passwordLabel: "Mật khẩu",
    roleLabel: "Vai trò",
    branchLabel: "Chi nhánh",
    firstLoginLabel: "Bắt buộc đổi mật khẩu",
    usernamePlaceholder: "Ví dụ: barber01",
    passwordPlaceholder: "Nhập mật khẩu ban đầu",
    branchPlaceholder: "Chọn chi nhánh",
    noBranchOption: "Chưa phân công",
    submitCreate: "Tạo nhân viên",
    submitUpdate: "Lưu thay đổi",
    cancelEdit: "Huỷ chỉnh sửa",
    edit: "Sửa",
    delete: "Xoá",
    deleteConfirm: "Bạn có chắc muốn xoá nhân viên này?",
    deleting: "Đang xoá...",
    loading: "Đang tải nhân viên...",
    empty: "Chưa có nhân viên nào.",
    createdAtLabel: "Ngày tạo",
    branchEmpty: "Chưa phân công chi nhánh",
    roles: {
      receptionist: "Lễ tân",
      barber: "Thợ cắt tóc",
      skinner: "Skinner",
    },
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      invalidRole: "Vai trò nhân viên không hợp lệ",
      missingPassword: "Vui lòng nhập mật khẩu",
      missingUsername: "Vui lòng nhập tên đăng nhập",
      passwordTooShort: "Mật khẩu phải có ít nhất 8 ký tự",
    },
  },
};
