export const staffTexts = {
  api: {
    errors: {
      duplicateUsername: "Tên đăng nhập đã tồn tại trong tiệm",
      forbidden: "Bạn không có quyền quản lý nhân viên",
      invalidBranch: "Chi nhánh không thuộc tiệm của bạn",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      invalidRole: "Vai trò nhân viên không hợp lệ",
      missingPassword: "Vui lòng nhập mật khẩu",
      missingStaffId: "Thiếu mã nhân viên",
      missingUsername: "Vui lòng nhập tên đăng nhập",
      missingFullName: "Vui lòng nhập họ tên đầy đủ",
      missingPhone: "Vui lòng nhập số điện thoại",
      missingDateOfBirth: "Vui lòng nhập ngày tháng năm sinh",
      invalidDateOfBirth: "Ngày tháng năm sinh không hợp lệ",
      invalidGender: "Vui lòng chọn giới tính",
      invalidIdentityImage: "Ảnh CCCD không hợp lệ",
      notFound: "Không tìm thấy nhân viên",
      passwordTooShort: "Mật khẩu phải có ít nhất 8 ký tự",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  ownerStaff: {
    title: "Quản lý nhân viên",
    description: "Tạo tài khoản và phân công chi nhánh cho nhân viên.",
    createTitle: "Thêm nhân viên",
    editTitle: "Cập nhật nhân viên",
    usernameLabel: "Tên đăng nhập",
    fullNameLabel: "Họ tên đầy đủ",
    phoneLabel: "Số điện thoại",
    dateOfBirthLabel: "Ngày tháng năm sinh",
    genderLabel: "Giới tính",
    hometownLabel: "Quê quán",
    currentAddressLabel: "Nơi ở hiện tại",
    identitySectionTitle: "Ảnh CCCD",
    personalSectionTitle: "Thông tin cá nhân",
    accountSectionTitle: "Tài khoản và phân công",
    identityFrontLabel: "CCCD mặt trước",
    identityBackLabel: "CCCD mặt sau",
    identityImageHint: "Chọn ảnh từ máy tính",
    identityImageAlt: "Ảnh {side}",
    backToList: "Quay lại danh sách nhân viên",
    passwordLabel: "Mật khẩu",
    roleLabel: "Vai trò",
    branchLabel: "Chi nhánh",
    managedBranchesLabel: "Chi nhánh quản lý",
    firstLoginLabel: "Bắt buộc đổi mật khẩu",
    usernamePlaceholder: "Ví dụ: barber01",
    fullNamePlaceholder: "Nhập họ tên đầy đủ",
    phonePlaceholder: "Nhập số điện thoại",
    genderPlaceholder: "Chọn giới tính",
    hometownPlaceholder: "Nhập quê quán",
    currentAddressPlaceholder: "Nhập nơi ở hiện tại",
    optionalSuffix: " (không bắt buộc)",
    genders: {
      male: "Nam",
      female: "Nữ",
      other: "Khác",
    },
    passwordPlaceholder: "Nhập mật khẩu ban đầu",
    branchPlaceholder: "Chọn chi nhánh",
    managedBranchesPlaceholder: "Chọn chi nhánh quản lý",
    noBranchOption: "Chưa phân công",
    allBranchesOption: "Tất cả",
    allRolesOption: "Tất cả",
    allStatusesOption: "Tất cả",
    applyFilters: "Áp dụng",
    createAction: "Thêm nhân viên",
    deleteCancel: "Huỷ",
    deleteConfirmTitle: "Ngưng làm nhân viên",
    deleteConfirmDescription:
      "Nhân viên sẽ được chuyển sang trạng thái nghỉ làm và không còn xuất hiện trong danh sách đang hoạt động.",
    detailTitle: "Chi tiết nhân viên",
    filterTitle: "Bộ lọc",
    listTitle: "Danh sách nhân viên",
    nextPage: "Sau",
    previousPage: "Trước",
    searchLabel: "Tìm kiếm",
    searchPlaceholder: "Tìm theo tên hoặc username",
    statusLabel: "Trạng thái",
    submitCreate: "Tạo nhân viên",
    submitUpdate: "Lưu thay đổi",
    cancelEdit: "Huỷ chỉnh sửa",
    edit: "Sửa",
    delete: "Ngưng làm",
    deleteConfirm: "Bạn có chắc muốn chuyển nhân viên này sang nghỉ làm?",
    deleting: "Đang cập nhật...",
    loading: "Đang tải nhân viên...",
    empty: "Chưa có nhân viên nào.",
    createdAtLabel: "Ngày tạo",
    branchEmpty: "Chưa phân công chi nhánh",
    firstLoginValue: "Cần đổi mật khẩu",
    pageSummary: "Hiển thị {start}-{end} trên {total} nhân viên",
    table: {
      actions: "Tùy chỉnh",
      branch: "Chi nhánh",
      createdAt: "Ngày tạo",
      index: "#",
      role: "Vai trò",
      status: "Trạng thái",
      username: "Tên nhân viên",
    },
    roles: {
      manager: "Quản lý",
      receptionist: "Lễ tân",
      barber: "Thợ cắt tóc",
      skinner: "Skinner",
    },
    statuses: {
      active: "Đang làm",
      initialized: "Khởi tạo",
      inactive: "Nghỉ làm",
    },
    toast: {
      created: "Đã tạo nhân viên",
      deleted: "Đã ngưng làm nhân viên",
      updated: "Đã cập nhật nhân viên",
    },
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      invalidRole: "Vai trò nhân viên không hợp lệ",
      missingBranch: "Vui lòng chọn chi nhánh",
      openVisits: "Nhân viên phải hoàn thành toàn bộ lượt ghé trước khi điều chuyển",
      invalidTransfer: "Danh sách nhân viên hoặc chi nhánh đích không hợp lệ",
      missingPassword: "Vui lòng nhập mật khẩu",
      missingUsername: "Vui lòng nhập tên đăng nhập",
      missingFullName: "Vui lòng nhập họ tên đầy đủ",
      missingPhone: "Vui lòng nhập số điện thoại",
      missingDateOfBirth: "Vui lòng nhập ngày tháng năm sinh",
      invalidGender: "Vui lòng chọn giới tính",
      invalidIdentityImage: "Chỉ chấp nhận file ảnh hợp lệ",
      identityImageTooLarge: "Mỗi ảnh CCCD không được vượt quá 10 MB",
      passwordTooShort: "Mật khẩu phải có ít nhất 8 ký tự",
    },
  },
};
