export const visitTexts = {
  api: {
    errors: {
      forbidden: "Bạn không có quyền tạo visit",
      invalidCombos: "Combo không thuộc tiệm của bạn",
      invalidCustomer: "Khách hàng không thuộc tiệm của bạn",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      invalidPhoto: "Vui lòng chọn file ảnh hợp lệ",
      invalidStaff: "Nhân viên không thuộc tiệm của bạn",
      invalidStatusTransition: "Không thể chuyển visit sang trạng thái này",
      invalidServices: "Dịch vụ không thuộc tiệm của bạn",
      lockedDetailEdit: "Visit đã hoàn thành, không thể chỉnh sửa dịch vụ/combo",
      lockedPhotoEdit: "Visit đã hoàn thành, không thể thêm hoặc xoá ảnh",
      lockedStaffEdit: "Đã hết thời gian chỉnh sửa barber/skinner",
      missingBranch: "Tài khoản chưa được phân công chi nhánh",
      missingCustomer: "Vui lòng chọn khách hàng",
      missingCompletionStaff:
        "Vui lòng chọn barber/skinner hoặc đánh dấu lý do không sử dụng dịch vụ trước khi hoàn thành visit",
      missingItems: "Vui lòng chọn ít nhất một dịch vụ hoặc combo",
      mixedItems: "Vui lòng chỉ chọn dịch vụ lẻ hoặc combo",
      notCompleted: "Chỉ chỉnh sửa barber/skinner sau khi visit hoàn thành",
      notFound: "Không tìm thấy visit",
      openVisitExists: "Khách hàng đang có visit chưa hoàn thành",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  create: {
    title: "Tạo visit mới",
    description: "Chọn dịch vụ hoặc combo và nhân sự phục vụ khách.",
    pageTitle: "Tạo visit",
    pageDescription: "Chọn khách hàng trước, sau đó chọn dịch vụ hoặc combo và nhân sự.",
    customerStepTitle: "Khách hàng",
    customerSearchLabel: "Tìm khách",
    customerSearchPlaceholder: "Nhập tên hoặc số điện thoại...",
    customerSearchButton: "Tìm",
    customerResultsLabel: (count: number) => `${count} khách phù hợp`,
    selectedCustomerLabel: "Khách đã chọn",
    selectedFromProfile: "Đã lấy thông tin khách từ hồ sơ.",
    selectCustomer: "Chọn khách",
    changeCustomer: "Đổi khách",
    emptyBeforeSearch: "Nhập tên hoặc số điện thoại để chọn khách tạo visit.",
    emptyAfterSearch: "Không tìm thấy khách phù hợp.",
    noLastVisit: "Chưa có lần ghé nào",
    servicesLabel: "Dịch vụ lẻ",
    combosLabel: "Combo",
    barberLabel: "Thợ cắt",
    skinnerLabel: "Skinner",
    barberPlaceholder: "Chọn thợ cắt",
    skinnerPlaceholder: "Chọn skinner",
    noHaircutOption: "Không cắt tóc",
    noSkinnerServiceOption: "Không skinner",
    totalPriceLabel: "Tổng tiền",
    submit: "Tạo visit",
    creating: "Đang tạo visit...",
    loadingOptions: "Đang tải dữ liệu tạo visit...",
    emptyServices: "Chưa có dịch vụ nào.",
    emptyCombos: "Chưa có combo nào.",
    success: "Tạo visit thành công",
    successDescription: "Visit mới đã được tạo ở trạng thái pending.",
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      missingItems: "Vui lòng chọn ít nhất một dịch vụ hoặc combo",
      mixedItems: "Chỉ chọn dịch vụ lẻ hoặc combo cho một visit",
    },
  },
  list: {
    title: "Danh sách visit",
    description: "Theo dõi visit đang chờ, đang làm và đã hoàn thành.",
    createVisit: "Tạo visit",
    customerLabel: "Khách",
    empty: "Chưa có visit nào ở trạng thái này.",
    loading: "Đang tải danh sách visit...",
    openDetail: "Mở chi tiết",
    photoWarning: "Thiếu ảnh",
    statuses: {
      pending: "Pending",
      inProgress: "Đang làm",
      completed: "Hoàn thành",
    },
  },
  detail: {
    title: "Chi tiết visit",
    description: "",
    backToCustomers: "Quay lại khách hàng",
    refreshDetail: "Cập nhật",
    refreshingDetail: "Đang cập nhật...",
    refreshSuccess: "Cập nhật chi tiết thành công",
    refreshSuccessDescription: "Thông tin visit đã được tải lại.",
    visitInfoTitle: "Thông tin chung",
    statusTitle: "Trạng thái",
    startVisit: "Thực hiện",
    completeVisit: "Hoàn thành",
    updatingStatus: "Đang cập nhật...",
    statusUpdateSuccess: "Cập nhật trạng thái thành công",
    statusUpdateSuccessDescription: "Trạng thái visit đã được cập nhật.",
    editVisitTitle: "Chỉnh sửa visit",
    editVisit: "Chỉnh sửa",
    closeEditVisit: "Đóng chỉnh sửa",
    saveEditVisit: "Lưu thay đổi",
    editSuccess: "Cập nhật visit thành công",
    editSuccessDescription: "Thông tin dịch vụ và nhân sự đã được cập nhật.",
    lockedEditVisit: "Visit đã hoàn thành, không thể chỉnh sửa dịch vụ/combo.",
    servicesTitle: "Dịch vụ",
    staffTitle: "Nhân sự",
    combosTitle: "Combo",
    barberTitle: "Thợ cắt",
    skinnerTitle: "Skinner",
    photosTitle: "Ảnh kiểu tóc",
    createdAtLabel: "Ngày tạo",
    completedAtLabel: "Hoàn thành lúc",
    totalPriceLabel: "Tổng tiền",
    lastUpdatedByLabel: "Người cập nhật cuối",
    noCompletedAt: "Chưa hoàn thành",
    noStaff: "Chưa chọn",
    noPhotos: "Chưa có ảnh kiểu tóc",
    noServices: "Chưa có dịch vụ",
    noCombos: "Chưa có combo",
    photoWarning: "Chưa upload ảnh kiểu tóc",
    uploadPhoto: "Upload ảnh",
    uploadingPhoto: "Đang upload...",
    uploadSuccess: "Upload ảnh thành công",
    uploadSuccessDescription: "Ảnh kiểu tóc đã được lưu vào visit.",
    deletePhoto: "Xoá ảnh",
    deletingPhoto: "Đang xoá...",
    deleteSuccess: "Xoá ảnh thành công",
    deleteSuccessDescription: "Ảnh kiểu tóc đã được xoá khỏi visit.",
    editStaff: "Chỉnh sửa nhân sự",
    closeEditStaff: "Đóng chỉnh sửa",
    loading: "Đang tải chi tiết visit...",
    status: {
      pending: "Pending",
      inProgress: "Đang làm",
      completed: "Hoàn thành",
    },
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      notFound: "Không tìm thấy visit",
    },
  },
  staffEdit: {
    title: "Chỉnh sửa nhân sự",
    remainingPrefix: "Còn",
    remainingSuffix: "để chỉnh sửa",
    hourUnit: "giờ",
    minuteUnit: "phút",
    locked: "Đã hết thời gian chỉnh sửa",
    submit: "Lưu nhân sự",
    saving: "Đang lưu...",
    success: "Đã cập nhật nhân sự",
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
    },
  },
};
