export const visitTexts = {
  api: {
    errors: {
      forbidden: "Bạn không có quyền tạo visit",
      invalidCombos: "Combo không thuộc tiệm của bạn",
      invalidCustomer: "Khách hàng không thuộc tiệm của bạn",
      invalidRequestBody: "Dữ liệu gửi lên không hợp lệ",
      invalidPhoto: "Vui lòng chọn file ảnh hợp lệ",
      invalidStaff: "Nhân viên không thuộc tiệm của bạn",
      invalidServices: "Dịch vụ không thuộc tiệm của bạn",
      lockedStaffEdit: "Đã hết thời gian chỉnh sửa barber/skinner",
      missingBranch: "Tài khoản chưa được phân công chi nhánh",
      missingCustomer: "Vui lòng chọn khách hàng",
      missingItems: "Vui lòng chọn ít nhất một dịch vụ hoặc combo",
      mixedItems: "Vui lòng chỉ chọn dịch vụ lẻ hoặc combo",
      notCompleted: "Chỉ chỉnh sửa barber/skinner sau khi visit hoàn thành",
      notFound: "Không tìm thấy visit",
      unauthorized: "Vui lòng đăng nhập để tiếp tục",
    },
  },
  create: {
    title: "Tạo visit mới",
    description: "Chọn dịch vụ hoặc combo và nhân sự phục vụ khách.",
    pageTitle: "Tạo visit",
    pageDescription: "Chọn khách hàng trước, sau đó chọn dịch vụ hoặc combo và nhân sự.",
    customerStepTitle: "Khách hàng",
    customerSearchLabel: "Tìm khách",
    customerSearchPlaceholder: "Nhập tên hoặc số điện thoại...",
    customerSearchButton: "Tìm",
    customerResultsLabel: (count: number) => `${count} khách phù hợp`,
    selectedCustomerLabel: "Khách đã chọn",
    selectedFromProfile: "Đã lấy thông tin khách từ hồ sơ.",
    selectCustomer: "Chọn khách",
    changeCustomer: "Đổi khách",
    emptyBeforeSearch: "Nhập tên hoặc số điện thoại để chọn khách tạo visit.",
    emptyAfterSearch: "Không tìm thấy khách phù hợp.",
    noLastVisit: "Chưa có lần ghé nào",
    servicesLabel: "Dịch vụ lẻ",
    combosLabel: "Combo",
    barberLabel: "Thợ cắt",
    skinnerLabel: "Skinner",
    noStaffOption: "Chọn sau",
    totalPriceLabel: "Tổng tiền",
    submit: "Tạo visit",
    creating: "Đang tạo visit...",
    loadingOptions: "Đang tải dữ liệu tạo visit...",
    emptyServices: "Chưa có dịch vụ nào.",
    emptyCombos: "Chưa có combo nào.",
    success: "Tạo visit thành công",
    successDescription: "Visit mới đã được tạo ở trạng thái pending.",
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      missingItems: "Vui lòng chọn ít nhất một dịch vụ hoặc combo",
      mixedItems: "Chỉ chọn dịch vụ lẻ hoặc combo cho một visit",
    },
  },
  detail: {
    title: "Chi tiết visit",
    description: "Thông tin dịch vụ, nhân sự và ảnh kiểu tóc của visit.",
    backToCustomers: "Quay lại khách hàng",
    visitInfoTitle: "Thông tin visit",
    statusTitle: "Trạng thái",
    servicesTitle: "Dịch vụ",
    combosTitle: "Combo",
    barberTitle: "Thợ cắt",
    skinnerTitle: "Skinner",
    photosTitle: "Ảnh kiểu tóc",
    createdAtLabel: "Ngày tạo",
    completedAtLabel: "Hoàn thành lúc",
    totalPriceLabel: "Tổng tiền",
    lastUpdatedByLabel: "Người cập nhật cuối",
    noCompletedAt: "Chưa hoàn thành",
    noStaff: "Chưa chọn",
    noPhotos: "Chưa có ảnh kiểu tóc",
    noServices: "Chưa có dịch vụ",
    noCombos: "Chưa có combo",
    photoWarning: "Chưa upload ảnh kiểu tóc",
    uploadPending: "Upload ảnh sẽ được bổ sung khi backend R2 sẵn sàng.",
    editStaff: "Chỉnh sửa nhân sự",
    closeEditStaff: "Đóng chỉnh sửa",
    loading: "Đang tải chi tiết visit...",
    status: {
      pending: "Pending",
      inProgress: "Đang làm",
      completed: "Hoàn thành",
    },
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
      notFound: "Không tìm thấy visit",
    },
  },
  staffEdit: {
    title: "Chỉnh sửa nhân sự",
    remainingPrefix: "Còn",
    remainingSuffix: "để chỉnh sửa",
    hourUnit: "giờ",
    minuteUnit: "phút",
    locked: "Đã hết thời gian chỉnh sửa",
    submit: "Lưu nhân sự",
    saving: "Đang lưu...",
    success: "Đã cập nhật nhân sự",
    errors: {
      generic: "Có lỗi xảy ra, vui lòng thử lại",
    },
  },
};
